# screen that shows the validity of a ticket and provides more info through the "more info" dropdown

<ValidInvalidUsedScreen>
    # expand or collapse "more info" dropdown
    Button:
        size_hint_y: 0.1
        pos_hint: {"x":0, "y":0.9}
        text: "Meer info"
        id: more_info_button
        font_name: 'app/assets/D-DIN.otf'
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.make_visible()

    # image to show the validity visually
    Image:
        id: validity_image
        source: ""
        fit_mode: "contain"
        size_hint_y: 0.7
        size_hint_x: 0.7
        pos_hint: {"x":0.15, "y":0.2}

    # (in dropdown) shows first name
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.87}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: voornaam_text
        text: "Voornaam: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.87}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: voornaam_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) shows last name
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.84}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: naam_text
        text: "Naam: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.84}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: naam_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) shows email
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.81}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: email_text
        text: "Email: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.81}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: email_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) shows lidstatus
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.78}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: lidstatus_text
        text: "Lidstatus: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.78}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: lidstatus_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) shows validity of ticket
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.75}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: validity_text
        text: "Geldigheid: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.75}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: validity_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) shows checkout status
    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.72}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: checkout_status_text
        text: "Status: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.72}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: checkout_status_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    # (in dropdown) button to execute changes
    Button:
        size_hint: 0.5, 0.05
        pos_hint: {"x":0.5, "y":0.1}
        text: "Sla op"
        id: validity_button
        opacity: 0
        disabled: True
        font_name: 'app/assets/D-DIN.otf'
        color: 1,1,1,1
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.change_validity_button()

    # button to go back to previous screen
    Button:
        size_hint_x: 1
        pos_hint: {"x":0, "y":0}
        size_hint_y: 0.1
        text: "Terug"
        font_name: 'app/assets/D-DIN.otf'
        color: 1,1,1,1
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.go_back()


# change how the datatable in the dropdown looks
<-MDDataTable>:
    background_color: 1, 1, 1, 1
    MDCard:
        id: container
        orientation: "vertical"
        elevation: 0
        padding: "5dp", "5dp", "5dp", "5dp"
        # canvas added for this change
        canvas:
            Color:
                rgba: root.background_color
            Rectangle:
                size: self.size
                pos: self.pos
