<ValidInvalidUsedScreen>
    Button:
        size_hint_y: 0.1
        pos_hint: {"x":0, "y":0.9}
        text: "Meer info"
        id: more_info_button
        font_name: 'app/assets/D-DIN.otf'
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.make_visible()

    Image:
        id: validity_image
        source: ""
        fit_mode: "contain"
        size_hint_y: 0.75
        size_hint_x: 0.7
        pos_hint: {"x":0.15, "y":0.15}

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.87}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: voornaam_text
        text: "Voornaam: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.87}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: voornaam_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.84}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: naam_text
        text: "Naam: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.84}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: naam_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.81}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: email_text
        text: "Email: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.81}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: email_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.78}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: lidstatus_text
        text: "Lidstatus: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.78}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: lidstatus_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.75}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: validity_text
        text: "Geldigheid: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.75}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: validity_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    MDLabel:
        size_hint_x: 0.3
        pos_hint: {"x":0, "y":0.72}
        text_size: self.size
        halign: "right"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: checkout_status_text
        text: "Status: "
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03
    MDLabel:
        size_hint_x: 0.7
        pos_hint: {"x":0.3, "y":0.72}
        text_size: self.size
        halign: "left"
        valign: "top"
        opacity: 0
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
        id: checkout_status_drop
        font_name: 'app/assets/D-DIN.otf'
        size_hint_y: 0.03

    TextInput:
        size_hint_y: None
		height:'30dp'
		size_hint_x: 0.15
		pos_hint: {"x":0.425, "y":0.1}
        id: count_input
        opacity: 0
        disabled: True
        text: "alle"
        multiline: False
        font_name: 'app/assets/D-DIN.otf'
        on_text_validate:
            root.change_validity_button()

    MDLabel:
        id: count_error
		size_hint_y: None
		height:'30dp'
		size_hint_x: 0.7
        pos_hint: {"x":0.15, "y":0.15}
		halign: 'center'
		color: 1,0,0,1
		opacity: 0
		text: "Kon aantal niet lezen"
		font_size: 45
		font_name: 'app/assets/D-DIN.otf'

    Button:
        size_hint: 0.425, 0.05
        pos_hint: {"x":0.575, "y":0.1}
        text: "Valideer"
        id: validity_button
        opacity: 0
        disabled: True
        font_name: 'app/assets/D-DIN.otf'
        color: 1,1,1,1
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.change_validity_button()

    Button:
        size_hint_x: 1
        pos_hint: {"x":0, "y":0}
        size_hint_y: 0.1
        text: "Terug"
        font_name: 'app/assets/D-DIN.otf'
        color: 1,1,1,1
        background_normal: 'app/assets/buttonnormal.png'
        background_down: 'app/assets/buttondown.png'
        on_release:
            root.set_invisible()
            root.manager.transition.direction = "right"
            root.manager.current = "scan"


<-MDDataTable>:
    background_color: 1, 1, 1, 1  # added for this example
    MDCard:
        id: container
        orientation: "vertical"
        elevation: 0
        padding: "5dp", "5dp", "5dp", "5dp"
        # canvas added for this change
        canvas:
            Color:
                rgba: root.background_color
            Rectangle:
                size: self.size
                pos: self.pos
